name: Intermediate environment variables
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数へセット
    steps:
      - run: echo "${ACTOR}"     # 環境変数経由でコンテキストのプロパティを参照
